#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}" )"
jshell=${jshell:-/opt/jdk-9/bin/jshell}
$jshell -version 2>/dev/null
if [ "$?" -eq 0 ]; then
  (cd .. && gradle testJar)
  $jshell -cp ../build/libs/rov-1.0.0-tests.jar imports.jsh
else
  echo "JShell could not be opened."
  echo "Please download jdk9 and export jshell location:"
  echo ""
  echo "export jshell=<your-install-dir>/jdk9/bin/jshell"
  echo ""
  echo "Download: https://jdk9.java.net/download/"
fi
