#!/usr/bin/env bash

sudo apt-get update
sudo apt-get dist-upgrade -y
sudo apt-get install -y \
'htop' \
'openjdk-8-jdk' \
'tree' \
'zip' \
# END_INSTALL

sudo apt-get autoremove
sudo apt-get autoclean

sudo hostnamectl 'set-hostname' "$1"

if [[ ! -d '.bin/gradle-2.6' ]]
then
    wget -q 'https://services.gradle.org/distributions/gradle-2.6-bin.zip'
    unzip -d '.bin' 'gradle-2.6-bin.zip' && rm 'gradle-2.6-bin.zip'
fi
