#!/usr/bin/env bash

set -e

sudo apt-get update
sudo apt-get dist-upgrade -y
sudo apt-get install -y \
'htop' \
'openjdk-8-jdk' \
'tree' \
'zip' \
# END_INSTALL

sudo apt-get autoremove
sudo apt-get autoclean

[[ $(hostname) = "$1" ]] || sudo hostnamectl 'set-hostname' "$1"

if [[ ! -d '.bin/gradle-2.9' ]]
then
    curl --remote-name --location --silent 'https://downloads.gradle.org/distributions/gradle-2.9-bin.zip'
    unzip -d '.bin' 'gradle-2.9-bin.zip' && rm 'gradle-2.9-bin.zip'
fi
